# Generated by Django 2.2.3 on 2019-07-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolha', '0002_auto_20190702_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.BinaryField(default='', null=True),
        ),
    ]
