# Generated by Django 2.2.3 on 2019-07-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolha', '0003_auto_20190702_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
