# Generated by Django 2.2.3 on 2019-07-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolha', '0006_auto_20190703_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='codigo_banco',
            field=models.IntegerField(default=0),
        ),
    ]
