# Generated by Django 2.2.3 on 2019-07-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolha', '0009_auto_20190703_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='comentario',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='foto',
            name='escolhido',
            field=models.CharField(default='', max_length=200),
        ),
    ]
