# Generated by Django 2.2.3 on 2019-07-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolha', '0011_auto_20190704_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='comentario',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
